// <auto-generated />
using System;
using ManiApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManiApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251029084939_AddStockMovementsOnly")]
    partial class AddStockMovementsOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ManiApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_ID");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("ManiApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_name");

                    b.HasKey("Id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("ManiApi.Models.ProductTopPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int>("QtyPerProduct")
                        .HasColumnType("int")
                        .HasColumnName("Qty_Per_product");

                    b.Property<int>("TopPartId")
                        .HasColumnType("int")
                        .HasColumnName("TopPart_ID");

                    b.Property<int>("VersionId")
                        .HasColumnType("int")
                        .HasColumnName("Version_ID");

                    b.HasKey("Id");

                    b.ToTable("producttopparts");
                });

            modelBuilder.Entity("ManiApi.Models.ProductVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("VersionComment")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("version_comment");

                    b.Property<DateOnly>("VersionDate")
                        .HasColumnType("date")
                        .HasColumnName("version_date");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("version_name");

                    b.Property<string>("VersionRasejums")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("version_rasejums");

                    b.HasKey("Id");

                    b.ToTable("versions");
                });

            modelBuilder.Entity("ManiApi.Models.StepType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("StepTypeName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("StepType_Name");

                    b.HasKey("Id");

                    b.ToTable("step_type");
                });

            modelBuilder.Entity("ManiApi.Models.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Move_Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Stock_Qty")
                        .HasColumnType("int");

                    b.Property<int>("Task_ID")
                        .HasColumnType("int");

                    b.Property<int>("Version_ID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("ManiApi.Models.TopPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("TopPartCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TopPart_Code");

                    b.Property<string>("TopPartName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TopPart_Name");

                    b.HasKey("Id");

                    b.ToTable("toppart");
                });

            modelBuilder.Entity("ManiApi.Models.TopPartStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("longtext")
                        .HasColumnName("Comments");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsFinal");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsMandatory");

                    b.Property<int>("ParallelGroup")
                        .HasColumnType("int")
                        .HasColumnName("Parallel_Group");

                    b.Property<int>("ProductToPartId")
                        .HasColumnType("int")
                        .HasColumnName("ProductToPart_ID");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Step_Name");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int")
                        .HasColumnName("Step_Order");

                    b.Property<int>("StepType")
                        .HasColumnType("int")
                        .HasColumnName("Step_Type");

                    b.Property<int>("WorkCentrId")
                        .HasColumnType("int")
                        .HasColumnName("WorkCentr_ID");

                    b.HasKey("Id");

                    b.ToTable("toppartsteps");
                });

            modelBuilder.Entity("ManiApi.Models.WorkCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("WorkCentr_Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("WorkCentr_Code");

                    b.Property<string>("WorkCentr_Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("WorkCentr_Name");

                    b.HasKey("Id");

                    b.ToTable("workcentr_type");
                });
#pragma warning restore 612, 618
        }
    }
}
