// <auto-generated />
using System;
using ManiApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManiApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515065818_AddVersionIdToOrderItems")]
    partial class AddVersionIdToOrderItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ManiApi.Models.Batch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Batches_Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Batches_Statuss")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.ToTable("batches");
                });

            modelBuilder.Entity("ManiApi.Models.BatchProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Batch_Id")
                        .HasColumnType("int");

                    b.Property<int>("Done_Qty")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int>("NormalOrder")
                        .HasColumnType("int");

                    b.Property<int>("Planned_Qty")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("ProductToPart_ID")
                        .HasColumnType("int");

                    b.Property<int>("Version_Id")
                        .HasColumnType("int");

                    b.Property<bool>("is_priority")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.ToTable("batches_products");
                });

            modelBuilder.Entity("ManiApi.Models.BatchProductLink", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ChildBatchProduct_ID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ParentBatchProduct_ID")
                        .HasColumnType("int");

                    b.Property<int>("Qty_Required")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("BatchProductLinks");
                });

            modelBuilder.Entity("ManiApi.Models.BatchProductMaterial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BatchProduct_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int>("SourceBatchProduct_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Task_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("BatchProductMaterials");
                });

            modelBuilder.Entity("ManiApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_ID");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("ManiApi.Models.CompanyCalendar", b =>
                {
                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("WorkDate");

                    b.Property<int?>("BreakMinutes")
                        .HasColumnType("int")
                        .HasColumnName("BreakMinutes");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("Notes");

                    b.Property<bool>("UseEmployeeDefaults")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("UseEmployeeDefaults");

                    b.Property<TimeSpan?>("WorkEnd")
                        .HasColumnType("time(6)")
                        .HasColumnName("WorkEnd");

                    b.Property<TimeSpan?>("WorkStart")
                        .HasColumnType("time(6)")
                        .HasColumnName("WorkStart");

                    b.HasKey("WorkDate");

                    b.ToTable("company_calendar");
                });

            modelBuilder.Entity("ManiApi.Models.CompanyCalendarBreak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("BreakEnd")
                        .HasColumnType("time(6)")
                        .HasColumnName("BreakEnd");

                    b.Property<TimeSpan>("BreakStart")
                        .HasColumnType("time(6)")
                        .HasColumnName("BreakStart");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("WorkDate");

                    b.HasKey("Id");

                    b.ToTable("company_calendar_breaks");
                });

            modelBuilder.Entity("ManiApi.Models.CustomerCodeMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("customer_code");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("customer_name");

                    b.Property<bool>("IsPart")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_part");

                    b.Property<bool>("IsProduct")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_product");

                    b.Property<int?>("ProductToPartId")
                        .HasColumnType("int")
                        .HasColumnName("producttopart_id");

                    b.Property<int?>("RalColorId")
                        .HasColumnType("int")
                        .HasColumnName("ral_color_id");

                    b.Property<int?>("TopPartId")
                        .HasColumnType("int")
                        .HasColumnName("top_part_id");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.ToTable("customer_code_map", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DefaultDailyHours")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("DefaultDailyHours");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Employee_Name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("UserName");

                    b.Property<int?>("WorkCentrTypeID")
                        .HasColumnType("int")
                        .HasColumnName("WorkCentrTypeID");

                    b.Property<TimeSpan?>("WorkEnd")
                        .HasColumnType("time(6)")
                        .HasColumnName("WorkEnd");

                    b.Property<TimeSpan?>("WorkStart")
                        .HasColumnType("time(6)")
                        .HasColumnName("WorkStart");

                    b.HasKey("Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("ManiApi.Models.EmployeeAvailability", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Hours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("employee_availability", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.EmployeeWorkLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BreakMinutes")
                        .HasColumnType("int");

                    b.Property<string>("BreaksJson")
                        .HasColumnType("longtext");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Hours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan?>("TimeFrom")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("TimeTo")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("employee_work_log", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("longtext")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("customer_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("order_number");

                    b.HasKey("Id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.OrderDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Created_At");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Customer_Name");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Order_Date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Order_Number");

                    b.HasKey("Id");

                    b.ToTable("order_drafts", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.OrderDraftItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Customer_Code");

                    b.Property<int?>("CustomerCodeMapId")
                        .HasColumnType("int")
                        .HasColumnName("customer_code_map_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Is_Active");

                    b.Property<bool>("IsMapped")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Is_Mapped");

                    b.Property<bool>("IsPart")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_part");

                    b.Property<bool>("IsProduct")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_product");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<int>("OrderDraftId")
                        .HasColumnType("int")
                        .HasColumnName("Order_Draft_ID");

                    b.Property<int?>("ProductToPartId")
                        .HasColumnType("int")
                        .HasColumnName("producttopart_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<int?>("RalColorId")
                        .HasColumnType("int")
                        .HasColumnName("Ral_Color_ID");

                    b.Property<int?>("TopPartId")
                        .HasColumnType("int")
                        .HasColumnName("top_part_id");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int")
                        .HasColumnName("Version_ID");

                    b.HasKey("Id");

                    b.ToTable("order_draft_items", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("customer_code");

                    b.Property<int?>("CustomerCodeMapId")
                        .HasColumnType("int")
                        .HasColumnName("customer_code_map_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_name");

                    b.HasKey("Id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("ManiApi.Models.ProductTopPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int>("QtyPerProduct")
                        .HasColumnType("int")
                        .HasColumnName("Qty_Per_product");

                    b.Property<int>("TopPartId")
                        .HasColumnType("int")
                        .HasColumnName("TopPart_ID");

                    b.Property<int>("VersionId")
                        .HasColumnType("int")
                        .HasColumnName("Version_ID");

                    b.HasKey("Id");

                    b.ToTable("producttopparts");
                });

            modelBuilder.Entity("ManiApi.Models.ProductVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_priority");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("VersionComment")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("version_comment");

                    b.Property<DateOnly>("VersionDate")
                        .HasColumnType("date")
                        .HasColumnName("version_date");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("version_name");

                    b.Property<string>("VersionRasejums")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("version_rasejums");

                    b.HasKey("Id");

                    b.ToTable("versions");
                });

            modelBuilder.Entity("ManiApi.Models.RalColor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("ID");

                    b.ToTable("ral_colors");
                });

            modelBuilder.Entity("ManiApi.Models.StageStepTypeMap", b =>
                {
                    b.Property<byte>("Stage")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int>("Step_Type_ID")
                        .HasColumnType("int")
                        .HasColumnName("Step_Type_ID");

                    b.HasKey("Stage");

                    b.HasIndex("Step_Type_ID");

                    b.ToTable("stage_step_type_map", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.StepType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("StepTypeName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("StepType_Name");

                    b.HasKey("Id");

                    b.ToTable("step_type");
                });

            modelBuilder.Entity("ManiApi.Models.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatchProduct_ID")
                        .HasColumnType("int")
                        .HasColumnName("BatchProduct_ID");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Created_At");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("Move_Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Move_Type");

                    b.Property<int?>("RAL_Color_ID")
                        .HasColumnType("int")
                        .HasColumnName("RAL_Color_ID");

                    b.Property<int?>("SourceBatchProduct_ID")
                        .HasColumnType("int")
                        .HasColumnName("SourceBatchProduct_ID");

                    b.Property<int>("Stock_Qty")
                        .HasColumnType("int")
                        .HasColumnName("Stock_Qty");

                    b.Property<int?>("Task_ID")
                        .HasColumnType("int")
                        .HasColumnName("Task_ID");

                    b.Property<int>("Version_ID")
                        .HasColumnType("int")
                        .HasColumnName("Version_ID");

                    b.HasKey("Id");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.TaskWorkSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("DurationMinutes");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("Employee_ID");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("EndTime");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("StartTime");

                    b.Property<int>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("Task_ID");

                    b.HasKey("Id");

                    b.ToTable("tasks_work_sessions");
                });

            modelBuilder.Entity("ManiApi.Models.Tasks", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("Assigned_To")
                        .HasColumnType("int")
                        .HasColumnName("Assigned_To");

                    b.Property<int>("BatchProduct_ID")
                        .HasColumnType("int")
                        .HasColumnName("BatchProduct_ID");

                    b.Property<int?>("Claimed_By")
                        .HasColumnType("int")
                        .HasColumnName("Claimed_By");

                    b.Property<DateTime?>("Finished_At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Finished_At");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<bool>("Is_Comment_For_Employee")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Is_Comment_For_Employee");

                    b.Property<int>("Qty_Done")
                        .HasColumnType("int")
                        .HasColumnName("Qty_Done");

                    b.Property<int>("Qty_Scrap")
                        .HasColumnType("int")
                        .HasColumnName("Qty_Scrap");

                    b.Property<int?>("RAL_Color_ID")
                        .HasColumnType("int")
                        .HasColumnName("RAL_Color_ID");

                    b.Property<DateTime?>("Started_At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Started_At");

                    b.Property<string>("Tasks_Comment")
                        .HasColumnType("longtext")
                        .HasColumnName("Tasks_Comment");

                    b.Property<int>("Tasks_Priority")
                        .HasColumnType("int")
                        .HasColumnName("Tasks_Priority");

                    b.Property<bool>("Tasks_Push")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Tasks_Push");

                    b.Property<int>("Tasks_Status")
                        .HasColumnType("int")
                        .HasColumnName("Tasks_Status");

                    b.Property<int>("TopPartStep_ID")
                        .HasColumnType("int")
                        .HasColumnName("TopPartStep_ID");

                    b.HasKey("ID");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("ManiApi.Models.TopPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<byte>("Stage")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("Stage");

                    b.Property<string>("TopPartCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TopPart_Code");

                    b.Property<string>("TopPartName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TopPart_Name");

                    b.Property<byte>("TopPartType")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("TopPartType");

                    b.HasKey("Id");

                    b.ToTable("toppart");
                });

            modelBuilder.Entity("ManiApi.Models.TopPartStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("longtext")
                        .HasColumnName("Comments");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("int")
                        .HasColumnName("Estimated_Minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsFinal");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsMandatory");

                    b.Property<bool>("IsPainting")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsPainting");

                    b.Property<int>("ParallelGroup")
                        .HasColumnType("int")
                        .HasColumnName("Parallel_Group");

                    b.Property<int>("ProductToPartId")
                        .HasColumnType("int")
                        .HasColumnName("ProductToPart_ID");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Step_Name");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int")
                        .HasColumnName("Step_Order");

                    b.Property<int>("StepType")
                        .HasColumnType("int")
                        .HasColumnName("Step_Type");

                    b.Property<int>("WorkCentrId")
                        .HasColumnType("int")
                        .HasColumnName("WorkCentr_ID");

                    b.HasKey("Id");

                    b.ToTable("toppartsteps");
                });

            modelBuilder.Entity("ManiApi.Models.WorkCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("Capacity");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int?>("Step_Type_ID")
                        .HasColumnType("int")
                        .HasColumnName("Step_Type_ID");

                    b.Property<int>("WorkCenter_Order")
                        .HasColumnType("int")
                        .HasColumnName("WorkCenter_Order");

                    b.Property<string>("WorkCentr_Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("WorkCentr_Code");

                    b.Property<string>("WorkCentr_Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("WorkCentr_Name");

                    b.HasKey("Id");

                    b.ToTable("workcentr_type");
                });

            modelBuilder.Entity("ManiApi.Models.StageStepTypeMap", b =>
                {
                    b.HasOne("ManiApi.Models.StepType", "StepType")
                        .WithMany()
                        .HasForeignKey("Step_Type_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StepType");
                });
#pragma warning restore 612, 618
        }
    }
}
