// <auto-generated />
using System;
using ManiApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManiApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901091750_AddStockMovementProducer")]
    partial class AddStockMovementProducer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ManiApi.Models.Batch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Batches_Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Batches_Statuss")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.ToTable("batches");
                });

            modelBuilder.Entity("ManiApi.Models.BatchProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Batch_Id")
                        .HasColumnType("int");

                    b.Property<int>("Done_Qty")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int>("NormalOrder")
                        .HasColumnType("int");

                    b.Property<int>("Planned_Qty")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("ProductToPart_ID")
                        .HasColumnType("int");

                    b.Property<int>("Version_Id")
                        .HasColumnType("int");

                    b.Property<bool>("is_priority")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.ToTable("batches_products");
                });

            modelBuilder.Entity("ManiApi.Models.BatchProductLink", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ChildBatchProduct_ID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ParentBatchProduct_ID")
                        .HasColumnType("int");

                    b.Property<int>("Qty_Required")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("BatchProductLinks");
                });

            modelBuilder.Entity("ManiApi.Models.BatchProductMaterial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BatchProduct_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int>("SourceBatchProduct_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Task_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("BatchProductMaterials");
                });

            modelBuilder.Entity("ManiApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_ID");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("ManiApi.Models.CompanyCalendar", b =>
                {
                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("WorkDate");

                    b.Property<int?>("BreakMinutes")
                        .HasColumnType("int")
                        .HasColumnName("BreakMinutes");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("Notes");

                    b.Property<bool>("UseEmployeeDefaults")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("UseEmployeeDefaults");

                    b.Property<TimeSpan?>("WorkEnd")
                        .HasColumnType("time(6)")
                        .HasColumnName("WorkEnd");

                    b.Property<TimeSpan?>("WorkStart")
                        .HasColumnType("time(6)")
                        .HasColumnName("WorkStart");

                    b.HasKey("WorkDate");

                    b.ToTable("company_calendar");
                });

            modelBuilder.Entity("ManiApi.Models.CompanyCalendarBreak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("BreakEnd")
                        .HasColumnType("time(6)")
                        .HasColumnName("BreakEnd");

                    b.Property<TimeSpan>("BreakStart")
                        .HasColumnType("time(6)")
                        .HasColumnName("BreakStart");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("WorkDate");

                    b.HasKey("Id");

                    b.ToTable("company_calendar_breaks");
                });

            modelBuilder.Entity("ManiApi.Models.CustomerCodeMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("customer_code");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("customer_name");

                    b.Property<bool>("IsPart")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_part");

                    b.Property<bool>("IsProduct")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_product");

                    b.Property<int?>("ProductToPartId")
                        .HasColumnType("int")
                        .HasColumnName("producttopart_id");

                    b.Property<int?>("RalColorId")
                        .HasColumnType("int")
                        .HasColumnName("ral_color_id");

                    b.Property<int?>("TopPartId")
                        .HasColumnType("int")
                        .HasColumnName("top_part_id");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.ToTable("customer_code_map", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DefaultDailyHours")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("DefaultDailyHours");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Employee_Name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("UserName");

                    b.Property<int?>("WorkCentrTypeID")
                        .HasColumnType("int")
                        .HasColumnName("WorkCentrTypeID");

                    b.Property<TimeSpan?>("WorkEnd")
                        .HasColumnType("time(6)")
                        .HasColumnName("WorkEnd");

                    b.Property<TimeSpan?>("WorkStart")
                        .HasColumnType("time(6)")
                        .HasColumnName("WorkStart");

                    b.HasKey("Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("ManiApi.Models.EmployeeAvailability", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Hours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("employee_availability", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.EmployeeWorkLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BreakMinutes")
                        .HasColumnType("int");

                    b.Property<string>("BreaksJson")
                        .HasColumnType("longtext");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Hours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan?>("TimeFrom")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("TimeTo")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("employee_work_log", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ItemCode");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ItemName");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ItemType_ID");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Unit");

                    b.HasKey("Id");

                    b.ToTable("items");
                });

            modelBuilder.Entity("ManiApi.Models.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("SortOrder");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TypeName");

                    b.HasKey("Id");

                    b.ToTable("itemtypes");
                });

            modelBuilder.Entity("ManiApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("longtext")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("customer_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("order_number");

                    b.HasKey("Id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.OrderDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Created_At");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Customer_Name");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Order_Date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Order_Number");

                    b.HasKey("Id");

                    b.ToTable("order_drafts", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.OrderDraftItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Customer_Code");

                    b.Property<int?>("CustomerCodeMapId")
                        .HasColumnType("int")
                        .HasColumnName("customer_code_map_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Is_Active");

                    b.Property<bool>("IsMapped")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Is_Mapped");

                    b.Property<bool>("IsPart")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_part");

                    b.Property<bool>("IsProduct")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_product");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<int>("OrderDraftId")
                        .HasColumnType("int")
                        .HasColumnName("Order_Draft_ID");

                    b.Property<int?>("ProductToPartId")
                        .HasColumnType("int")
                        .HasColumnName("producttopart_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<int?>("RalColorId")
                        .HasColumnType("int")
                        .HasColumnName("Ral_Color_ID");

                    b.Property<int?>("TopPartId")
                        .HasColumnType("int")
                        .HasColumnName("top_part_id");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int")
                        .HasColumnName("Version_ID");

                    b.HasKey("Id");

                    b.ToTable("order_draft_items", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("customer_code");

                    b.Property<int?>("CustomerCodeMapId")
                        .HasColumnType("int")
                        .HasColumnName("customer_code_map_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_name");

                    b.HasKey("Id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("ManiApi.Models.ProductTopPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttachToNodeId")
                        .HasColumnType("int")
                        .HasColumnName("AttachToNode_ID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int?>("ParentProductTopPartId")
                        .HasColumnType("int")
                        .HasColumnName("Parent_ProductTopPart_ID");

                    b.Property<int>("QtyPerProduct")
                        .HasColumnType("int")
                        .HasColumnName("Qty_Per_product");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("SortOrder");

                    b.Property<int>("TopPartId")
                        .HasColumnType("int")
                        .HasColumnName("TopPart_ID");

                    b.Property<int>("VersionId")
                        .HasColumnType("int")
                        .HasColumnName("Version_ID");

                    b.HasKey("Id");

                    b.ToTable("producttopparts");
                });

            modelBuilder.Entity("ManiApi.Models.ProductTopPartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AreaM2")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("AreaM2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("Item_ID");

                    b.Property<decimal?>("LengthM")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("LengthM");

                    b.Property<uint>("ProductTopPartId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("ProductTopPart_ID");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Qty");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("SortOrder");

                    b.HasKey("Id");

                    b.ToTable("producttoppartitems");
                });

            modelBuilder.Entity("ManiApi.Models.ProductVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_priority");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("ProductionModel")
                        .HasColumnType("int")
                        .HasColumnName("production_model");

                    b.Property<string>("VersionComment")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("version_comment");

                    b.Property<DateOnly>("VersionDate")
                        .HasColumnType("date")
                        .HasColumnName("version_date");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("version_name");

                    b.Property<string>("VersionRasejums")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("version_rasejums");

                    b.HasKey("Id");

                    b.ToTable("versions");
                });

            modelBuilder.Entity("ManiApi.Models.ProductionBatch", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("ID"));

                    b.Property<string>("Batch_Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<sbyte>("Batch_Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("End_Date")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("Start_Date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("Batch_Code")
                        .IsUnique()
                        .HasDatabaseName("UX_production_batches_code");

                    b.ToTable("production_batches", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.ProductionBatchTopPart", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("ID"));

                    b.Property<uint>("Batch_ID")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<uint>("Done_Qty")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("Planned_Qty")
                        .HasColumnType("int unsigned");

                    b.Property<int>("TopPart_ID")
                        .HasColumnType("int");

                    b.Property<int>("Workflow_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Batch_ID");

                    b.HasIndex("TopPart_ID");

                    b.HasIndex("Workflow_ID");

                    b.ToTable("production_batch_topparts", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.ProductionComponentStaging", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("ID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("ProductionExecution_ID")
                        .HasColumnType("int unsigned");

                    b.Property<decimal>("RequiredQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int?>("StagedByEmployee_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("StagedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("Staged_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkflowProcessComponent_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StagedByEmployee_ID");

                    b.HasIndex("WorkflowProcessComponent_ID");

                    b.HasIndex("ProductionExecution_ID", "WorkflowProcessComponent_ID")
                        .IsUnique()
                        .HasDatabaseName("UX_component_staging_execution_process_component");

                    b.ToTable("production_component_staging", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.ProductionExecution", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("ID"));

                    b.Property<DateTime?>("Completed_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("ProductionBatchTopPart_ID")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ProductionRequirement_ID")
                        .HasColumnType("int unsigned");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Started_At")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TopPart_ID")
                        .HasColumnType("int");

                    b.Property<int>("Workflow_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductionBatchTopPart_ID")
                        .HasDatabaseName("IX_production_executions_batch_toppart");

                    b.HasIndex("ProductionRequirement_ID")
                        .HasDatabaseName("IX_production_executions_requirement");

                    b.HasIndex("TopPart_ID")
                        .HasDatabaseName("IX_production_executions_top_part");

                    b.HasIndex("Workflow_ID")
                        .HasDatabaseName("IX_production_executions_workflow");

                    b.HasIndex("Status", "IsActive")
                        .HasDatabaseName("IX_production_executions_status");

                    b.ToTable("production_executions", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.ProductionPlanningDraft", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("ID"));

                    b.Property<DateTime?>("Approved_At")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Batch_Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Draft_Type")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly?>("Plan_Date")
                        .HasColumnType("date");

                    b.Property<uint?>("Source_Batch_ID")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("ID");

                    b.HasIndex("Source_Batch_ID");

                    b.ToTable("production_planning_drafts", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.ProductionPlanningDraftItem", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("ID"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("Draft_ID")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Planned_Qty")
                        .HasColumnType("int");

                    b.Property<int>("TopPart_ID")
                        .HasColumnType("int");

                    b.Property<int>("Workflow_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Draft_ID");

                    b.HasIndex("TopPart_ID");

                    b.HasIndex("Workflow_ID");

                    b.ToTable("production_planning_draft_items", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.ProductionRequirement", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("ID"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GrossQuantity")
                        .HasColumnType("int");

                    b.Property<int>("IncomingCoveredQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NetQuantity")
                        .HasColumnType("int");

                    b.Property<uint?>("ParentRequirement_ID")
                        .HasColumnType("int unsigned");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<uint?>("ProductionBatchTopPart_ID")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ProductionPlanningDraftItem_ID")
                        .HasColumnType("int unsigned");

                    b.Property<int>("RequiredTopPart_ID")
                        .HasColumnType("int");

                    b.Property<int>("SourceTopPart_ID")
                        .HasColumnType("int");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StockCoveredQuantity")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowProcessComponent_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ParentRequirement_ID")
                        .HasDatabaseName("IX_production_requirements_parent");

                    b.HasIndex("ProductionBatchTopPart_ID")
                        .HasDatabaseName("IX_production_requirements_batch_toppart");

                    b.HasIndex("ProductionPlanningDraftItem_ID")
                        .HasDatabaseName("IX_production_requirements_draft_item");

                    b.HasIndex("SourceTopPart_ID")
                        .HasDatabaseName("IX_production_requirements_source");

                    b.HasIndex("WorkflowProcessComponent_ID")
                        .HasDatabaseName("IX_production_requirements_process_component");

                    b.HasIndex("Priority", "Created_At")
                        .HasDatabaseName("IX_production_requirements_priority");

                    b.HasIndex("RequiredTopPart_ID", "IsActive")
                        .HasDatabaseName("IX_production_requirements_required");

                    b.ToTable("production_requirements", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.ProductionReservation", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("ID"));

                    b.Property<int>("ConsumedQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Consumed_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("ProductionRequirement_ID")
                        .HasColumnType("int unsigned");

                    b.Property<int>("ReleasedQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Released_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("int");

                    b.Property<uint>("SourceMovement_ID")
                        .HasColumnType("int unsigned");

                    b.Property<int?>("SourceWorkflowNode_ID")
                        .HasColumnType("int");

                    b.Property<int?>("SourceWorkflow_ID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TopPart_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductionRequirement_ID")
                        .HasDatabaseName("IX_production_reservations_requirement");

                    b.HasIndex("SourceWorkflowNode_ID");

                    b.HasIndex("SourceWorkflow_ID", "SourceWorkflowNode_ID")
                        .HasDatabaseName("IX_production_reservations_workflow_node");

                    b.HasIndex("SourceMovement_ID", "Status", "IsActive")
                        .HasDatabaseName("IX_production_reservations_source");

                    b.HasIndex("TopPart_ID", "Status", "IsActive")
                        .HasDatabaseName("IX_production_reservations_top_part");

                    b.ToTable("production_reservations", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.RalColor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("ID");

                    b.ToTable("ral_colors");
                });

            modelBuilder.Entity("ManiApi.Models.StageStepTypeMap", b =>
                {
                    b.Property<byte>("Stage")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int>("Step_Type_ID")
                        .HasColumnType("int")
                        .HasColumnName("Step_Type_ID");

                    b.HasKey("Stage");

                    b.HasIndex("Step_Type_ID");

                    b.ToTable("stage_step_type_map", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.StepType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("StepTypeName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("StepType_Name");

                    b.HasKey("Id");

                    b.ToTable("step_type");
                });

            modelBuilder.Entity("ManiApi.Models.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatchProduct_ID")
                        .HasColumnType("int")
                        .HasColumnName("BatchProduct_ID");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Created_At");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("Move_Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Move_Type");

                    b.Property<int?>("RAL_Color_ID")
                        .HasColumnType("int")
                        .HasColumnName("RAL_Color_ID");

                    b.Property<int?>("SourceBatchProduct_ID")
                        .HasColumnType("int")
                        .HasColumnName("SourceBatchProduct_ID");

                    b.Property<int>("Stock_Qty")
                        .HasColumnType("int")
                        .HasColumnName("Stock_Qty");

                    b.Property<int?>("Task_ID")
                        .HasColumnType("int")
                        .HasColumnName("Task_ID");

                    b.Property<int>("Version_ID")
                        .HasColumnType("int")
                        .HasColumnName("Version_ID");

                    b.HasKey("Id");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.StockMovementNew", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("ID"));

                    b.Property<uint?>("ConsumedByBatch_ID")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Movement_Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint?>("ProducedByTaskNew_ID")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ProductionBatchTopPart_ID")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ProductionReservation_ID")
                        .HasColumnType("int unsigned");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("RAL_Color_ID")
                        .HasColumnType("int");

                    b.Property<uint?>("ReversalOfMovement_ID")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("SourceMovement_ID")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("TaskNew_ID")
                        .HasColumnType("int unsigned");

                    b.Property<int>("TopPart_ID")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowNode_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ConsumedByBatch_ID");

                    b.HasIndex("ProductionBatchTopPart_ID");

                    b.HasIndex("ProductionReservation_ID");

                    b.HasIndex("RAL_Color_ID");

                    b.HasIndex("ReversalOfMovement_ID")
                        .IsUnique()
                        .HasDatabaseName("UX_stock_reversal_movement");

                    b.HasIndex("SourceMovement_ID")
                        .HasDatabaseName("IX_stock_source_movement");

                    b.HasIndex("TaskNew_ID")
                        .HasDatabaseName("IX_stock_movements_new_task");

                    b.HasIndex("TopPart_ID");

                    b.HasIndex("WorkflowNode_ID");

                    b.HasIndex("ProducedByTaskNew_ID", "WorkflowNode_ID")
                        .IsUnique()
                        .HasDatabaseName("UX_stock_movements_new_producer_output");

                    b.HasIndex("TaskNew_ID", "ProductionReservation_ID")
                        .IsUnique()
                        .HasDatabaseName("UX_stock_movements_new_task_reservation");

                    b.ToTable("stock_movements_new", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.TaskNew", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("ID"));

                    b.Property<DateTime?>("Assigned_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Completed_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("Paused_At")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("ProductionExecution_ID")
                        .HasColumnType("int unsigned");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Started_At")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("WorkCenter_ID")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowNode_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WorkflowNode_ID");

                    b.HasIndex("ProductionExecution_ID", "WorkflowNode_ID")
                        .HasDatabaseName("IX_tasks_new_execution_node");

                    b.HasIndex("Employee_ID", "Status", "IsActive")
                        .HasDatabaseName("IX_tasks_new_employee_status");

                    b.HasIndex("WorkCenter_ID", "Status", "IsActive")
                        .HasDatabaseName("IX_tasks_new_workcenter_status");

                    b.ToTable("tasks_new", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.TaskNewDependency", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("ID"));

                    b.Property<uint>("DependsOnTaskNew_ID")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TaskNew_ID")
                        .HasColumnType("int unsigned");

                    b.HasKey("ID");

                    b.HasIndex("DependsOnTaskNew_ID")
                        .HasDatabaseName("IX_tasks_new_dependencies_depends_on");

                    b.HasIndex("TaskNew_ID", "DependsOnTaskNew_ID")
                        .IsUnique()
                        .HasDatabaseName("UX_tasks_new_dependencies_pair");

                    b.ToTable("tasks_new_dependencies", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.TaskNewStatusHistory", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("ID"));

                    b.Property<int?>("ChangedByEmployee_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Changed_At")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FromStatus")
                        .HasColumnType("longtext");

                    b.Property<uint>("TaskNew_ID")
                        .HasColumnType("int unsigned");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("ChangedByEmployee_ID")
                        .HasDatabaseName("IX_tasks_new_status_history_employee");

                    b.HasIndex("TaskNew_ID", "Changed_At")
                        .HasDatabaseName("IX_tasks_new_status_history_task");

                    b.ToTable("tasks_new_status_history", (string)null);
                });

            modelBuilder.Entity("ManiApi.Models.TaskWorkSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("DurationMinutes");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("Employee_ID");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("EndTime");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("StartTime");

                    b.Property<int>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("Task_ID");

                    b.HasKey("Id");

                    b.ToTable("tasks_work_sessions");
                });

            modelBuilder.Entity("ManiApi.Models.Tasks", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("Assigned_To")
                        .HasColumnType("int")
                        .HasColumnName("Assigned_To");

                    b.Property<int>("BatchProduct_ID")
                        .HasColumnType("int")
                        .HasColumnName("BatchProduct_ID");

                    b.Property<int?>("Claimed_By")
                        .HasColumnType("int")
                        .HasColumnName("Claimed_By");

                    b.Property<DateTime?>("Finished_At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Finished_At");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<bool>("Is_Comment_For_Employee")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Is_Comment_For_Employee");

                    b.Property<int>("Qty_Done")
                        .HasColumnType("int")
                        .HasColumnName("Qty_Done");

                    b.Property<int>("Qty_Scrap")
                        .HasColumnType("int")
                        .HasColumnName("Qty_Scrap");

                    b.Property<int?>("RAL_Color_ID")
                        .HasColumnType("int")
                        .HasColumnName("RAL_Color_ID");

                    b.Property<int?>("Source_ProductToPart_ID")
                        .HasColumnType("int")
                        .HasColumnName("Source_ProductToPart_ID");

                    b.Property<DateTime?>("Started_At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Started_At");

                    b.Property<string>("Tasks_Comment")
                        .HasColumnType("longtext")
                        .HasColumnName("Tasks_Comment");

                    b.Property<int>("Tasks_Priority")
                        .HasColumnType("int")
                        .HasColumnName("Tasks_Priority");

                    b.Property<bool>("Tasks_Push")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Tasks_Push");

                    b.Property<int>("Tasks_Status")
                        .HasColumnType("int")
                        .HasColumnName("Tasks_Status");

                    b.Property<int>("TopPartStep_ID")
                        .HasColumnType("int")
                        .HasColumnName("TopPartStep_ID");

                    b.HasKey("ID");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("ManiApi.Models.TopPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<byte>("Stage")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("Stage");

                    b.Property<int?>("TopPartCategoryID")
                        .HasColumnType("int")
                        .HasColumnName("TopPartCategoryID");

                    b.Property<string>("TopPartCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TopPart_Code");

                    b.Property<string>("TopPartName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TopPart_Name");

                    b.Property<byte>("TopPartType")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("TopPartType");

                    b.HasKey("Id");

                    b.ToTable("toppart");
                });

            modelBuilder.Entity("ManiApi.Models.TopPartCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Category_Name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.HasKey("Id");

                    b.ToTable("toppartcategory");
                });

            modelBuilder.Entity("ManiApi.Models.TopPartSparePart", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<uint>("ProductTopPartId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("ProductTopPart_ID");

                    b.Property<uint>("SparePartTopPartId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("SparePartTopPart_ID");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("Workflow_ID");

                    b.HasKey("Id");

                    b.ToTable("toppart_sparepart");
                });

            modelBuilder.Entity("ManiApi.Models.TopPartStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("longtext")
                        .HasColumnName("Comments");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("int")
                        .HasColumnName("Estimated_Minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsFinal");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsMandatory");

                    b.Property<bool>("IsPainting")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsPainting");

                    b.Property<int>("ParallelGroup")
                        .HasColumnType("int")
                        .HasColumnName("Parallel_Group");

                    b.Property<int>("ProductToPartId")
                        .HasColumnType("int")
                        .HasColumnName("ProductToPart_ID");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Step_Name");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int")
                        .HasColumnName("Step_Order");

                    b.Property<int>("StepType")
                        .HasColumnType("int")
                        .HasColumnName("Step_Type");

                    b.Property<int>("WorkCentrId")
                        .HasColumnType("int")
                        .HasColumnName("WorkCentr_ID");

                    b.HasKey("Id");

                    b.ToTable("toppartsteps");
                });

            modelBuilder.Entity("ManiApi.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("ManiApi.Models.WorkCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("Capacity");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int?>("Step_Type_ID")
                        .HasColumnType("int")
                        .HasColumnName("Step_Type_ID");

                    b.Property<int>("WorkCenter_Order")
                        .HasColumnType("int")
                        .HasColumnName("WorkCenter_Order");

                    b.Property<string>("WorkCentr_Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("WorkCentr_Code");

                    b.Property<string>("WorkCentr_Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("WorkCentr_Name");

                    b.HasKey("Id");

                    b.ToTable("workcentr_type");
                });

            modelBuilder.Entity("ManiApi.Models.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Created_Date");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsCurrent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Workflow_Name");

                    b.Property<int?>("ParentNodeId")
                        .HasColumnType("int")
                        .HasColumnName("ParentNode_ID");

                    b.Property<int?>("ParentWorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("ParentWorkflow_ID");

                    b.Property<DateTime?>("ReleasedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Released_Date");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<uint?>("TopPartId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("TopPart_ID");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int")
                        .HasColumnName("Version_ID");

                    b.Property<int>("WorkflowVersion")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowVersion");

                    b.HasKey("Id");

                    b.ToTable("workflows");
                });

            modelBuilder.Entity("ManiApi.Models.WorkflowComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("ComponentType")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("ComponentType");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("Item_ID");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Quantity");

                    b.Property<int?>("ReferencedWorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("ReferencedWorkflow_ID");

                    b.Property<int?>("RequiredWorkflowNodeId")
                        .HasColumnType("int")
                        .HasColumnName("RequiredWorkflowNode_ID");

                    b.Property<uint?>("TopPartId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("TopPart_ID");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("Workflow_ID");

                    b.HasKey("Id");

                    b.ToTable("workflowcomponents");
                });

            modelBuilder.Entity("ManiApi.Models.WorkflowDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DependsOnNodeId")
                        .HasColumnType("int")
                        .HasColumnName("DependsOnNode_ID");

                    b.Property<int>("NodeId")
                        .HasColumnType("int")
                        .HasColumnName("Node_ID");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("Workflow_ID");

                    b.HasKey("Id");

                    b.HasIndex("NodeId", "DependsOnNodeId")
                        .IsUnique();

                    b.ToTable("workflowdependencies");
                });

            modelBuilder.Entity("ManiApi.Models.WorkflowNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("longtext")
                        .HasColumnName("Comments");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("int")
                        .HasColumnName("EstimatedMinutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<byte>("NodeType")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("NodeType");

                    b.Property<int?>("OutputProductToPartId")
                        .HasColumnType("int")
                        .HasColumnName("Output_ProductTopPart_ID");

                    b.Property<int?>("ParentNodeId")
                        .HasColumnType("int")
                        .HasColumnName("ParentNode_ID");

                    b.Property<int?>("ProductToPartId")
                        .HasColumnType("int")
                        .HasColumnName("ProductToPart_ID");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("SortOrder");

                    b.Property<uint?>("StepTypeId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("StepType_ID");

                    b.Property<uint?>("TopPartId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("TopPart_ID");

                    b.Property<int?>("WorkCenterId")
                        .HasColumnType("int")
                        .HasColumnName("WorkCenter_ID");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("Workflow_ID");

                    b.HasKey("Id");

                    b.ToTable("workflownodes");
                });

            modelBuilder.Entity("ManiApi.Models.WorkflowNodeConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FromNodeId")
                        .HasColumnType("int")
                        .HasColumnName("FromNode_ID");

                    b.Property<int>("ToNodeId")
                        .HasColumnType("int")
                        .HasColumnName("ToNode_ID");

                    b.HasKey("Id");

                    b.ToTable("workflownodeconnections");
                });

            modelBuilder.Entity("ManiApi.Models.WorkflowProcessComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProcessNodeId")
                        .HasColumnType("int")
                        .HasColumnName("ProcessNode_ID");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Quantity");

                    b.Property<int>("WorkflowComponentId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowComponent_ID");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowComponentId");

                    b.ToTable("workflowprocesscomponents");
                });

            modelBuilder.Entity("ManiApi.Models.ProductionBatchTopPart", b =>
                {
                    b.HasOne("ManiApi.Models.ProductionBatch", "Batch")
                        .WithMany()
                        .HasForeignKey("Batch_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManiApi.Models.TopPart", "TopPart")
                        .WithMany()
                        .HasForeignKey("TopPart_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManiApi.Models.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("Workflow_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("TopPart");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("ManiApi.Models.ProductionComponentStaging", b =>
                {
                    b.HasOne("ManiApi.Models.ProductionExecution", "ProductionExecution")
                        .WithMany()
                        .HasForeignKey("ProductionExecution_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManiApi.Models.Employee", "StagedByEmployee")
                        .WithMany()
                        .HasForeignKey("StagedByEmployee_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.WorkflowProcessComponent", "WorkflowProcessComponent")
                        .WithMany()
                        .HasForeignKey("WorkflowProcessComponent_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionExecution");

                    b.Navigation("StagedByEmployee");

                    b.Navigation("WorkflowProcessComponent");
                });

            modelBuilder.Entity("ManiApi.Models.ProductionExecution", b =>
                {
                    b.HasOne("ManiApi.Models.ProductionBatchTopPart", "ProductionBatchTopPart")
                        .WithMany()
                        .HasForeignKey("ProductionBatchTopPart_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.ProductionRequirement", "ProductionRequirement")
                        .WithMany()
                        .HasForeignKey("ProductionRequirement_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.TopPart", "TopPart")
                        .WithMany()
                        .HasForeignKey("TopPart_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManiApi.Models.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("Workflow_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionBatchTopPart");

                    b.Navigation("ProductionRequirement");

                    b.Navigation("TopPart");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("ManiApi.Models.ProductionPlanningDraft", b =>
                {
                    b.HasOne("ManiApi.Models.ProductionBatch", "SourceBatch")
                        .WithMany()
                        .HasForeignKey("Source_Batch_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SourceBatch");
                });

            modelBuilder.Entity("ManiApi.Models.ProductionPlanningDraftItem", b =>
                {
                    b.HasOne("ManiApi.Models.ProductionPlanningDraft", "Draft")
                        .WithMany()
                        .HasForeignKey("Draft_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManiApi.Models.TopPart", "TopPart")
                        .WithMany()
                        .HasForeignKey("TopPart_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManiApi.Models.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("Workflow_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Draft");

                    b.Navigation("TopPart");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("ManiApi.Models.ProductionRequirement", b =>
                {
                    b.HasOne("ManiApi.Models.ProductionRequirement", "ParentRequirement")
                        .WithMany("ChildRequirements")
                        .HasForeignKey("ParentRequirement_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.ProductionBatchTopPart", "ProductionBatchTopPart")
                        .WithMany()
                        .HasForeignKey("ProductionBatchTopPart_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.ProductionPlanningDraftItem", "ProductionPlanningDraftItem")
                        .WithMany()
                        .HasForeignKey("ProductionPlanningDraftItem_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.TopPart", "RequiredTopPart")
                        .WithMany()
                        .HasForeignKey("RequiredTopPart_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManiApi.Models.TopPart", "SourceTopPart")
                        .WithMany()
                        .HasForeignKey("SourceTopPart_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManiApi.Models.WorkflowProcessComponent", "WorkflowProcessComponent")
                        .WithMany()
                        .HasForeignKey("WorkflowProcessComponent_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentRequirement");

                    b.Navigation("ProductionBatchTopPart");

                    b.Navigation("ProductionPlanningDraftItem");

                    b.Navigation("RequiredTopPart");

                    b.Navigation("SourceTopPart");

                    b.Navigation("WorkflowProcessComponent");
                });

            modelBuilder.Entity("ManiApi.Models.ProductionReservation", b =>
                {
                    b.HasOne("ManiApi.Models.ProductionRequirement", "ProductionRequirement")
                        .WithMany()
                        .HasForeignKey("ProductionRequirement_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManiApi.Models.StockMovementNew", "SourceMovement")
                        .WithMany()
                        .HasForeignKey("SourceMovement_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManiApi.Models.WorkflowNode", "SourceWorkflowNode")
                        .WithMany()
                        .HasForeignKey("SourceWorkflowNode_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.Workflow", "SourceWorkflow")
                        .WithMany()
                        .HasForeignKey("SourceWorkflow_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.TopPart", "TopPart")
                        .WithMany()
                        .HasForeignKey("TopPart_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionRequirement");

                    b.Navigation("SourceMovement");

                    b.Navigation("SourceWorkflow");

                    b.Navigation("SourceWorkflowNode");

                    b.Navigation("TopPart");
                });

            modelBuilder.Entity("ManiApi.Models.StageStepTypeMap", b =>
                {
                    b.HasOne("ManiApi.Models.StepType", "StepType")
                        .WithMany()
                        .HasForeignKey("Step_Type_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StepType");
                });

            modelBuilder.Entity("ManiApi.Models.StockMovementNew", b =>
                {
                    b.HasOne("ManiApi.Models.ProductionBatch", "ConsumedByBatch")
                        .WithMany()
                        .HasForeignKey("ConsumedByBatch_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.TaskNew", "ProducedByTaskNew")
                        .WithMany()
                        .HasForeignKey("ProducedByTaskNew_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.ProductionBatchTopPart", "ProductionBatchTopPart")
                        .WithMany()
                        .HasForeignKey("ProductionBatchTopPart_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.ProductionReservation", "ProductionReservation")
                        .WithMany()
                        .HasForeignKey("ProductionReservation_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.RalColor", "RalColor")
                        .WithMany()
                        .HasForeignKey("RAL_Color_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.StockMovementNew", "ReversalOfMovement")
                        .WithMany()
                        .HasForeignKey("ReversalOfMovement_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.StockMovementNew", "SourceMovement")
                        .WithMany()
                        .HasForeignKey("SourceMovement_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.TaskNew", "TaskNew")
                        .WithMany()
                        .HasForeignKey("TaskNew_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.TopPart", "TopPart")
                        .WithMany()
                        .HasForeignKey("TopPart_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManiApi.Models.WorkflowNode", "WorkflowNode")
                        .WithMany()
                        .HasForeignKey("WorkflowNode_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ConsumedByBatch");

                    b.Navigation("ProducedByTaskNew");

                    b.Navigation("ProductionBatchTopPart");

                    b.Navigation("ProductionReservation");

                    b.Navigation("RalColor");

                    b.Navigation("ReversalOfMovement");

                    b.Navigation("SourceMovement");

                    b.Navigation("TaskNew");

                    b.Navigation("TopPart");

                    b.Navigation("WorkflowNode");
                });

            modelBuilder.Entity("ManiApi.Models.TaskNew", b =>
                {
                    b.HasOne("ManiApi.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.ProductionExecution", "ProductionExecution")
                        .WithMany()
                        .HasForeignKey("ProductionExecution_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManiApi.Models.WorkCenter", "WorkCenter")
                        .WithMany()
                        .HasForeignKey("WorkCenter_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManiApi.Models.WorkflowNode", "WorkflowNode")
                        .WithMany()
                        .HasForeignKey("WorkflowNode_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ProductionExecution");

                    b.Navigation("WorkCenter");

                    b.Navigation("WorkflowNode");
                });

            modelBuilder.Entity("ManiApi.Models.TaskNewDependency", b =>
                {
                    b.HasOne("ManiApi.Models.TaskNew", "DependsOnTaskNew")
                        .WithMany()
                        .HasForeignKey("DependsOnTaskNew_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManiApi.Models.TaskNew", "TaskNew")
                        .WithMany()
                        .HasForeignKey("TaskNew_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DependsOnTaskNew");

                    b.Navigation("TaskNew");
                });

            modelBuilder.Entity("ManiApi.Models.TaskNewStatusHistory", b =>
                {
                    b.HasOne("ManiApi.Models.Employee", "ChangedByEmployee")
                        .WithMany()
                        .HasForeignKey("ChangedByEmployee_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManiApi.Models.TaskNew", "TaskNew")
                        .WithMany()
                        .HasForeignKey("TaskNew_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByEmployee");

                    b.Navigation("TaskNew");
                });

            modelBuilder.Entity("ManiApi.Models.WorkflowProcessComponent", b =>
                {
                    b.HasOne("ManiApi.Models.WorkflowComponent", "WorkflowComponent")
                        .WithMany()
                        .HasForeignKey("WorkflowComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowComponent");
                });

            modelBuilder.Entity("ManiApi.Models.ProductionRequirement", b =>
                {
                    b.Navigation("ChildRequirements");
                });
#pragma warning restore 612, 618
        }
    }
}
